apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pytorch-job
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    pytorch: ["--master=master", "--worker=worker", "--port=23456"] # Pytorch plugin register
    svc: []
  queue: default
  tasks:
    - replicas: 1
      name: master
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - image: gueraf/torchx_tmp@sha256:a0ce322918f39b9a22c8ab97c86760781d7bbeb2875ec45dd75ea02b15e89a8b
              imagePullPolicy: IfNotPresent
              name: master
              command: [
                  "python3",
                  "/home/ray/ddp_allreduce.py",
                  "--environment_variables_csv=NCCL_DEBUG=TRACE,NCCL_NET=IB",
                  "--sleep_forever=True",
                  # "--do_work=False",
                ]
              securityContext:
                capabilities:
                  add: ["IPC_LOCK", "CAP_SETGID", "CAP_SETUID"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
                limits:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
            - name: rdma-test
              image: gueraf/perftest@sha256:a8ad5d13cabab9e2a00bb69ad8e2c40d75b2dda38c73c78b3fda2f9a01605c7b
              securityContext:
                capabilities:
                  add: ["IPC_LOCK"]
              resources:
                limits:
                  "rdma/rdma_shared_device_a": "1"
                requests:
                  "rdma/rdma_shared_device_a": "1"
              command:
                - sh
                - -c
                - |
                  ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
                  sleep infinity
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          # good node(s0
                          # - th03-bluorion-w41.gmicloud.ai
                          # bad node(s)
                          - th03-bluorion-w12.gmicloud.ai
                          # - th03-bluorion-w17.gmicloud.ai
                          # - th03-bluorion-w20.gmicloud.ai
                          # - th03-bluorion-w30.gmicloud.ai
                          # - th03-bluorion-w38.gmicloud.ai
                          # - th03-bluorion-w43.gmicloud.ai
          restartPolicy: Never
    - replicas: 7
      name: worker
      template:
        spec:
          containers:
            - image: gueraf/torchx_tmp@sha256:a0ce322918f39b9a22c8ab97c86760781d7bbeb2875ec45dd75ea02b15e89a8b
              imagePullPolicy: IfNotPresent
              name: worker
              command: [
                  "python3",
                  "/home/ray/ddp_allreduce.py",
                  "--environment_variables_csv=NCCL_DEBUG=TRACE,NCCL_NET=IB",
                  "--sleep_forever=True",
                  # "--do_work=False",
                ]
              securityContext:
                capabilities:
                  add: ["IPC_LOCK", "CAP_SETGID", "CAP_SETUID"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
                limits:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
            - name: rdma-test
              image: gueraf/perftest@sha256:a8ad5d13cabab9e2a00bb69ad8e2c40d75b2dda38c73c78b3fda2f9a01605c7b
              securityContext:
                capabilities:
                  add: ["IPC_LOCK"]
              resources:
                limits:
                  "rdma/rdma_shared_device_a": "1"
                requests:
                  "rdma/rdma_shared_device_a": "1"
              command:
                - sh
                - -c
                - |
                  ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
                  sleep infinity
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          # good node(s0
                          # - th03-bluorion-w41.gmicloud.ai
                          # bad node(s)
                          - th03-bluorion-w12.gmicloud.ai
                          # - th03-bluorion-w17.gmicloud.ai
                          # - th03-bluorion-w20.gmicloud.ai
                          # - th03-bluorion-w30.gmicloud.ai
                          # - th03-bluorion-w38.gmicloud.ai
                          # - th03-bluorion-w43.gmicloud.ai
          restartPolicy: Never
