apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: pytorch-job
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    pytorch: ["--master=master", "--worker=worker", "--port=23456"] # Pytorch plugin register
    svc: []
  queue: default
  tasks:
    - replicas: 1
      name: master
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - image: gueraf/torchx_tmp@sha256:a0ce322918f39b9a22c8ab97c86760781d7bbeb2875ec45dd75ea02b15e89a8b
              imagePullPolicy: IfNotPresent
              name: master
              command:
                [
                  "python3",
                  "/home/ray/ddp_allreduce.py",
                  "--num_integers=10",
                  "--environment_variables_csv=NCCL_DEBUG=TRACE,NCCL_NET=IB",
                  "--sleep_forever=True",
                  "--do_work=True",
                  "--print_info_only=False",
                ]
              securityContext:
                capabilities:
                  add: ["IPC_LOCK", "CAP_SETGID", "CAP_SETUID"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
                limits:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: ray-gpu-status
                        operator: In
                        values:
                          - volcano
    - replicas: 3
          restartPolicy: Never
      name: worker
      template:
        spec:
          containers:
            - image: gueraf/torchx_tmp@sha256:a0ce322918f39b9a22c8ab97c86760781d7bbeb2875ec45dd75ea02b15e89a8b
              imagePullPolicy: IfNotPresent
              name: worker
              command:
                [
                  "python3",
                  "/home/ray/ddp_allreduce.py",
                  "--num_integers=10",
                  "--environment_variables_csv=NCCL_DEBUG=TRACE,NCCL_NET=IB",
                  "--sleep_forever=True",
                  "--do_work=True",
                  "--print_info_only=False",
                ]
              securityContext:
                capabilities:
                  add: ["IPC_LOCK", "CAP_SETGID", "CAP_SETUID"]
              resources:
                requests:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
                limits:
                  nvidia.com/gpu: 1
                  "rdma/rdma_shared_device_a": "1"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: ray-gpu-status
                        operator: In
                        values:
                          - volcano
          restartPolicy: Never
